version: '3.1'

services:
  db:
    image: mysql:8.0
    volumes:
      - my-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tenkei-project
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "33307:3306"

volumes:
  my-db: